name: Cargo Compete Test

on:
  push:
    branches:
      - main
      - "**"
  pull_request:
    branches:
      - main
      - "**"
    paths:
      - '**/src/bin/**.rs'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cargo Compete
        run: cargo install cargo-compete

      - name: Get list of changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            BASE_SHA=$(git rev-parse HEAD^)
            HEAD_SHA=$(git rev-parse HEAD)
          fi
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"
          git diff --name-only $BASE_SHA $HEAD_SHA > changed_files.txt
          cat changed_files.txt

      - name: Extract problem names
        id: extract-problems
        run: |
          problems=$(grep '^.*/src/bin/.*\.rs$' changed_files.txt | sed 's|.*/src/bin/\(.*\)\.rs$|\1|' | uniq | tr '\n' ' ')
          echo "problems=$problems" >> $GITHUB_OUTPUT
          echo "Detected problems: $problems"

      - name: Run Cargo Compete Test for changed problems
        if: steps.extract-problems.outputs.problems != ''
        working-directory: tessoku-book
        run: |
          for problem in ${{ steps.extract-problems.outputs.problems }}; do
            echo "Testing problem: $problem"
            cargo compete test "$problem"
          done

      - name: No problems changed
        if: steps.extract-problems.outputs.problems == ''
        run: echo "No AtCoder problems were changed. Skipping tests."